Repository victoricoma/helprback, pull requests merged in 2022-09, with the labels that each got.

#111 Criacao Procedure para chamar com chamados em andamento semana
  mysql/script_helpr/sps_chamados_andamento_semanal.sql
Labels: documentation, enhancement

#113 Criação de procedure que listará os chamados do tecnico em aberto no …
  mysql/script_helpr/sps_relatorio_aberto_tecnico_tres_dias.sql
Labels: documentation

#115 Gatilho e tabela de LOG
  mysql/script_helpr/tg_log_chamado_alteracao_prioridade.sql
Labels: documentation, enhancement

#120 Criação do endpoint de requisição dos dados via email e sua estrutura…
  src/main/java/com/api/helprback/domain/dtos/PessoaDTO.java
  src/main/java/com/api/helprback/resources/PessoaResource.java
  src/main/java/com/api/helprback/services/PessoaService.java
Labels: documentation, enhancement

#121 Criação de tabela de log e triggers para perfis em pessoas.
  mysql/script_helpr/trg_relatorio_pessoa_perfil.sql
Labels: documentation, enhancement

#123 Chamado Tecnico ultimos três dias.
  src/main/java/com/api/helprback/repositories/ChamadoRepository.java
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#125 Procedure chamados abertos
  mysql/script_helpr/sps_chamado_aberto_cliente.sql
Labels: enhancement

#127 Criação de procedure para relatório de chamado de técnicos agrupados por prioridade.
  mysql/script_helpr/sps_relatorio_chamados_prioridade_tecnico.sql
Labels: documentation, enhancement

#128 Endpoints para a entrega da listagem de logs
  src/main/java/com/api/helprback/domain/LogUpdateStatus.java
  src/main/java/com/api/helprback/repositories/LogUpdateStatusRepository.java
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#129 Procedure Chamados Ultimos Tres Dias de cada Tecnico.
  mysql/script_helpr/sps_chamados_ultimos_tres_dias.sql
Labels: documentation, enhancement

#133 Correção do direcionamento da Query.
  src/main/java/com/api/helprback/repositories/ChamadoRepository.java
Labels: bug

#135 Criada classe entidade de FuturosCandidatos e endpoints para adição n…
  src/main/java/com/api/helprback/config/SecurityConfig.java
  src/main/java/com/api/helprback/domain/FuturosCandidatos.java
  src/main/java/com/api/helprback/domain/dtos/FuturosCandidatosDTO.java
  src/main/java/com/api/helprback/repositories/FuturosCandidatosRepository.java
  src/main/java/com/api/helprback/resources/FuturosCandidatosResource.java
  src/main/java/com/api/helprback/services/FuturosCandidatosService.java
Labels: documentation, enhancement

#137 Implementação de teste para testar o retorno de findByEmail em pessoas.
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: enhancement

#142 Correção do Trigger de alteração de status de chamados
  mysql/script_helpr/trigger_update_status_chamado.sql
Labels: bug, wontfix

#143 Criação de trigger e tabela de log para observação de alteração de cl…
  mysql/script_helpr/log_alteracao_cliente_tecnico.sql
Labels: documentation

#146 banco de dados- chamados urgentes
  mysql/script_helpr/sps_chamados_urgentes_prioridade_alta_tres_dias.sql
Labels: documentation

#150 Adição de crud para novos clientes.
  src/main/java/com/api/helprback/config/SecurityConfig.java
  src/main/java/com/api/helprback/domain/NovosClientes.java
  src/main/java/com/api/helprback/domain/dtos/NovosClientesDTO.java
  src/main/java/com/api/helprback/repositories/NovosClientesRopository.java
  src/main/java/com/api/helprback/resources/NovosClientesResource.java
  src/main/java/com/api/helprback/services/NovosClientesService.java
Labels: documentation, enhancement

#152 Adição de uma procedure que traga alteração de perfil de pessoa em intervalo de datas.
  mysql/script_helpr/sps_relatorio_pessoa_perfil.sql
Labels: documentation, enhancement

#156 Adição do Endpoint do relatório agrupado por prioridade e atualização da procedure.
  mysql/script_helpr/sps_relatorio_chamados_prioridade_tecnico.sql
  src/main/java/com/api/helprback/domain/RelatorioBaseTecnicoChamado.java
  src/main/java/com/api/helprback/repositories/RelatorioBaseTecnicoChamadoRepository.java
  src/main/java/com/api/helprback/resources/RelatorioBaseTecnicoChamadoResource.java
  src/main/java/com/api/helprback/services/RelatorioBaseTecnicoChamadoService.java
Labels: documentation, enhancement

#157 Adição do Endpoint do relatório agrupado por status e atualização da …
  mysql/script_helpr/sps_relatorio_status_chamados_tecnicos.sql
  src/main/java/com/api/helprback/repositories/RelatorioBaseTecnicoChamadoRepository.java
  src/main/java/com/api/helprback/resources/RelatorioBaseTecnicoChamadoResource.java
  src/main/java/com/api/helprback/services/RelatorioBaseTecnicoChamadoService.java
Labels: documentation, enhancement

#158 Endpoint da tabela de Log.
  mysql/script_helpr/tg_log_chamado_alteracao_prioridade.sql
  mysql/script_helpr/tg_log_chamado_prioridade.sql
  src/main/java/com/api/helprback/domain/LogChamadoPrioridade.java
  src/main/java/com/api/helprback/repositories/LogChamadoPrioridadeRepository.java
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#161 "Teste de endpoint para o relatorio de chamados por Tecnico"
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation

#163 Pre Autorizacoes back
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/resources/ClienteResource.java
Labels: documentation, enhancement

#164 Correção da procedure de chamados de prioridade alta dos últimos três dias
  mysql/script_helpr/sps_chamados_urgentes_prioridade_alta_tres_dias.sql
Labels: bug

#168 Endpoint para proc de Chamados status aberto
  mysql/script_helpr/sps_relatorio_aberto_tecnico_tres_dias.sql
  src/main/java/com/api/helprback/repositories/ChamadoRepository.java
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#169 Teste entrega de serviço chamado aberto e prioridade alta
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation

#170 criacao de teste relatorio montagem chamados
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation

#172 Foi criado um endpoint para o teste de futuros candidatos.
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation, enhancement

#173 Criação de teste listagem com e sem ID.
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation

#174 Teste Chamados Ultimos Tres Dias.
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: enhancement

#177 Adição de uma procedure que traga alteração de prioridade de chamado em um intervalo de datas.
  mysql/script_helpr/sps_chamado_prioridade.sql
Labels: documentation, enhancement

#178 Adição de uma procedure que traga alteração de cliente e técnicos nos chamado, em intervalo de datas.
  mysql/script_helpr/sps_alteracao_cliente_tecnico.sql
Labels: documentation

#179 Criação do endpoint para chamados urgentes dos últimos 3 dias por id do técnico
  src/main/java/com/api/helprback/repositories/ChamadoRepository.java
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/services/ChamadoService.java
Labels: enhancement

#181 Adição do teste de ChamadoByCLienteId
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation, enhancement

#183 Testagem concluída do relatório dos 3 dias para um técnico.
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: enhancement

#185 Dominio Mnesagem.
  src/main/java/com/api/helprback/domain/Mensagem.java
  src/main/java/com/api/helprback/domain/Tecnico.java
  src/main/java/com/api/helprback/domain/dtos/MensagemDTO.java
Labels: enhancement

#186 Endpoint de cliente logado/token.
  src/main/java/com/api/helprback/repositories/ChamadoRepository.java
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#187 adicao de endpoint troca de perfil
  src/main/java/com/api/helprback/domain/LogPessoa.java
  src/main/java/com/api/helprback/domain/dtos/LogPessoaDTO.java
  src/main/java/com/api/helprback/repositories/LogPessoaRepository.java
  src/main/java/com/api/helprback/resources/LogPessoaResource.java
  src/main/java/com/api/helprback/services/LogPessoaService.java
Labels: documentation

#189 Correção de metodos duplicados
  src/main/java/com/api/helprback/repositories/ChamadoRepository.java
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/resources/application-dev.properties
Labels: bug

#190 Adição do testNovosClientesFindAll
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation, enhancement

#191 Criação de teste para futuros clientes.
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: enhancement

#193 Crie do serviço de CRUD para mensagens onde somente o ADM envie mensa…
  src/main/java/com/api/helprback/domain/Mensagem.java
  src/main/java/com/api/helprback/repositories/MensagemRepository.java
  src/main/java/com/api/helprback/resources/MensagemResource.java
  src/main/java/com/api/helprback/services/MensagemService.java
Labels: enhancement
