Repository victoricoma/helprback, pull requests merged in 2022-08, with the labels that each got.

#4 Montagem do projeto inicial do back
  helprback/mysql/empregados/Script de Procedires e Tabelas Temporarias.sql
  helprback/pom.xml
  helprback/src/main/java/com/api/helprback/HelprbackApplication.java
Labels: documentation, enhancement

#8 Adição das classes enumeradoras do sistema.
  helprback/src/main/java/com/api/helprback/domain/Pessoa.java
  helprback/src/main/java/com/api/helprback/domain/enums/Perfil.java
  helprback/src/main/java/com/api/helprback/domain/enums/Prioridade.java
  helprback/src/main/java/com/api/helprback/domain/enums/Status.java
Labels: documentation, enhancement

#12 Nova estrutura de classes base MySQL
  helprback/src/main/java/com/api/helprback/domain/Chamado.java
  helprback/src/main/java/com/api/helprback/domain/Cliente.java
  helprback/src/main/java/com/api/helprback/domain/Tecnico.java
Labels: documentation, enhancement

#15 Estruturação das classes para persistência de Entidades.
  helprback/src/main/java/com/api/helprback/domain/Chamado.java
  helprback/src/main/java/com/api/helprback/domain/Cliente.java
  helprback/src/main/java/com/api/helprback/domain/Pessoa.java
  helprback/src/main/java/com/api/helprback/domain/Tecnico.java
  helprback/src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation, enhancement

#19 Conexão das classes com os dados no H2 console.
  helprback/src/main/resources/application.properties
Labels: documentation, enhancement

#21 Injeção de dados no banco de h2 testes.
  helprback/src/main/java/com/api/helprback/HelprbackApplication.java
  helprback/src/main/java/com/api/helprback/repositories/ChamadoRepository.java
  helprback/src/main/java/com/api/helprback/repositories/ClienteRepository.java
  helprback/src/main/java/com/api/helprback/repositories/PessoaRepository.java
  helprback/src/main/java/com/api/helprback/repositories/TecnicoRepository.java
Labels: documentation, enhancement

#23 Modulação de dados para serviços e configuradores.
  helprback/src/main/java/com/api/helprback/HelprbackApplication.java
  helprback/src/main/java/com/api/helprback/config/TestConfig.java
  helprback/src/main/java/com/api/helprback/services/DBService.java
  helprback/src/main/resources/application-test.properties
  helprback/src/main/resources/application.properties
Labels: documentation, enhancement

#26 Configuração de DEV para direcionar os dados.
  helprback/src/main/java/com/api/helprback/config/DevConfig.java
  helprback/src/main/java/com/api/helprback/domain/Tecnico.java
  helprback/src/main/java/com/api/helprback/services/DBService.java
  helprback/src/main/resources/application-dev.properties
  helprback/src/main/resources/application-test.properties
  helprback/src/main/resources/application.properties
Labels: documentation, enhancement

#29 Adição dos serviço e recurso de listagem por id em tecnico.
  helprback/src/main/java/com/api/helprback/domain/Pessoa.java
  helprback/src/main/java/com/api/helprback/domain/Tecnico.java
  helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
  helprback/src/main/java/com/api/helprback/services/TecnicoService.java
  helprback/src/main/resources/application-dev.properties
Labels: documentation, enhancement

#33 Montagem e configuração dos dados da classe DTO.
  helprback/src/main/java/com/api/helprback/domain/dtos/TecnicoDTO.java
  helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
Labels: documentation, enhancement

#35 Tratamento de bug de erro para entrega ao front.
  helprback/src/main/java/com/api/helprback/resources/exceptions/ResourceExceptionHandler.java
  helprback/src/main/java/com/api/helprback/resources/exceptions/StandardError.java
  helprback/src/main/java/com/api/helprback/services/TecnicoService.java
  helprback/src/main/java/com/api/helprback/services/exceptions/ObjectNotFoundException.java
Labels: bug, enhancement

#42 Listagem geral e criação de Tecnicos.
  helprback/src/main/java/com/api/helprback/domain/Tecnico.java
  helprback/src/main/java/com/api/helprback/domain/dtos/TecnicoDTO.java
  helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
  helprback/src/main/java/com/api/helprback/services/TecnicoService.java
  helprback/src/main/resources/application.properties
Labels: documentation, enhancement

#44 Validação no insert de CPF e E-mail
  helprback/src/main/java/com/api/helprback/repositories/PessoaRepository.java
  helprback/src/main/java/com/api/helprback/resources/exceptions/ResourceExceptionHandler.java
  helprback/src/main/java/com/api/helprback/services/TecnicoService.java
  helprback/src/main/java/com/api/helprback/services/exceptions/DataIntegrityViolationException.java
Labels: bug, enhancement

#48 Adição do update de Tecnico ao serviço e recurso na API
  helprback/src/main/java/com/api/helprback/domain/Pessoa.java
  helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
  helprback/src/main/java/com/api/helprback/services/TecnicoService.java
Labels: documentation, enhancement

#50 Adição do recurso e serviço de delete do técnico.
  helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
  helprback/src/main/java/com/api/helprback/services/TecnicoService.java
Labels: documentation, enhancement, wontfix

#56 CRUD de cliente exercício prático.
  helprback/src/main/java/com/api/helprback/domain/Cliente.java
  helprback/src/main/java/com/api/helprback/domain/dtos/ClienteDTO.java
  helprback/src/main/java/com/api/helprback/resources/ClienteResource.java
  helprback/src/main/java/com/api/helprback/services/ClienteService.java
Labels: documentation, enhancement

#58 Serviço de relatório do Chamado por Id com relacionamento.
  helprback/src/main/java/com/api/helprback/domain/dtos/ChamadoDTO.java
  helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
  helprback/src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#62 Listagem geral de Chamados para tabela.
  helprback/src/main/java/com/api/helprback/domain/dtos/TecnicoDTO.java
  helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
  helprback/src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#64 Adição de novos chamados com relacionamento conferido.
  helprback/src/main/java/com/api/helprback/domain/dtos/ChamadoDTO.java
  helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
  helprback/src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#66 Adição da manipulação de dados.
  helprback/src/main/java/com/api/helprback/domain/Chamado.java
  helprback/src/main/java/com/api/helprback/resources/ChamadoResource.java
  helprback/src/main/java/com/api/helprback/services/ChamadoService.java
Labels: documentation, enhancement

#70 Deeploy do banco e segurança de endpoint.
  helprback/pom.xml
  helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
  helprback/src/main/resources/application-dev.properties
Labels: documentation, enhancement, wontfix

#73 Adição dos serviços de identificação de usuário.
  helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
  helprback/src/main/java/com/api/helprback/security/UserSS.java
  helprback/src/main/java/com/api/helprback/services/ClienteService.java
  helprback/src/main/java/com/api/helprback/services/DBService.java
  helprback/src/main/java/com/api/helprback/services/TecnicoService.java
Labels: documentation, enhancement, wontfix

#74 Chaves de credenciais e token construtor.
  helprback/src/main/java/com/api/helprback/domain/dtos/CredenciaisDTO.java
  helprback/src/main/java/com/api/helprback/security/JWTUtil.java
  helprback/src/main/java/com/api/helprback/services/UserDetailsServiceImpl.java
  helprback/src/main/resources/application.properties
Labels: documentation, enhancement, wontfix

#76 JWT token de autenticação e métodos de acesso http.
  helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
  helprback/src/main/java/com/api/helprback/security/JWTAuthenticationFilter.java
Labels: bug, documentation, enhancement, wontfix

#77 Aplicação interna de regras de transito na aplicação.
  helprback/src/main/java/com/api/helprback/config/SecurityConfig.java
  helprback/src/main/java/com/api/helprback/resources/TecnicoResource.java
  helprback/src/main/java/com/api/helprback/security/JWTAuthenticationFilter.java
  helprback/src/main/java/com/api/helprback/security/JWTAuthorizationFilter.java
  helprback/src/main/java/com/api/helprback/security/JWTUtil.java
  helprback/src/main/java/com/api/helprback/security/UserSS.java
  helprback/src/main/resources/application.properties
Labels: bug, documentation, enhancement, wontfix

#80 Configuração de deploy para o Heroku.
  helprback/system.properties
Labels: documentation, enhancement

#82 Construção do banco no Azure MySQL
  src/main/resources/application.properties
Labels: documentation

#83 Inicialização do banco.
  src/main/resources/application-dev.properties
Labels: documentation

#85 Interligação de relatórios de procedures.
  mysql/script_helpr/sps_relatorio_andamento_tecnico_semanal.sql
  src/main/java/com/api/helprback/repositories/ChamadoRepository.java
Labels: documentation, enhancement

#87 Relatório de chamados por técnico na semana.
  src/main/java/com/api/helprback/resources/ChamadoResource.java
  src/main/java/com/api/helprback/services/ChamadoService.java
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation, enhancement

#89 Adição do Relatório de Técnicos com chmados urgentes.
  src/main/java/com/api/helprback/repositories/TecnicoRepository.java
  src/main/java/com/api/helprback/resources/TecnicoResource.java
  src/main/java/com/api/helprback/services/TecnicoService.java
  src/test/java/com/api/helprback/HelprbackApplicationTests.java
Labels: documentation, enhancement

#104 Adicionado encoder de senhas no método update dos serviços de cliente…
  src/main/java/com/api/helprback/services/ClienteService.java
  src/main/java/com/api/helprback/services/TecnicoService.java
Labels: bug

#107 Script de procedure de contagem de chamados por status.
  mysql/script_helpr/sps_relatorio_status_chamados_tecnicos.sql
Labels: documentation, enhancement

#108 Tabela de log do status do chamado e criação do trigger de alteração status
  mysql/script_helpr/trigger_update_status_chamado.sql
Labels: documentation, enhancement
